name: 'Add all, commit and push changes'

inputs:
  message:
    description: 'The commit message'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          git add -A
          git commit -m "${{ inputs.message }}"
          git push origin
        fi
      shell: bash
