name: 'Create a tag'

inputs:
  tag-name:
    description: 'The name of the tag to create'
    required: true
  message:
    description: 'An optional message to go with the tag'
    default: ''

runs:
  using: "composite"
  steps:
    - run: git tag -a ${{ inputs.tag-name }} ${{ github.sha }} -m "${{ inputs.message }}"
      shell: bash
    - run: git push origin refs/tags/${{ inputs.tag-name }}
      shell: bash
