name: 'Create or update a tag'
description: 'Create a new tag or update it'

inputs:
  tag-name:
    description: 'The name of the tag to create'
    required: true
  message:
    description: 'An optional message to go with the tag'
    default: ''

runs:
  using: "composite"
  steps:
    - run: git tag --delete refs/tags/${{ inputs.tag-name }} 2>/dev/null || true
      shell: bash
    - run: git tag -a ${{ inputs.tag-name }} ${{ github.sha }} -m "${{ inputs.message }}"
      shell: bash
    - run: git push origin refs/tags/${{ inputs.tag-name }} --force
      shell: bash
