name: 'Create a GitHub release'

inputs:
  tag-name:
    description: 'The tag name of the release'
    required: true
  generate-release-notes:
    description: 'Automatically generate release notes from commits'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Create GitHub release
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: '${{ inputs.tag-name }}',
            name: '${{ inputs.tag-name }}',
            prerelease: '${{ inputs.tag-name }}'.includes('-'),
            generate_release_notes: '${{ inputs.generate-release-notes }}' === 'true'
          })
