name: 'Create a GitHub release'
description: 'Create a new GitHub release'

inputs:
  version:
    description: 'The version of the release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create GitHub release
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: 'v${{ inputs.version }}',
            name: 'v${{ inputs.version }}',
            prerelease: '${{ inputs.version }}'.includes('-')
          })
