name: 'Create a GitHub release'

inputs:
  tag-name:
    description: 'The tag name of the release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create GitHub release
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: 'v${{ inputs.tag-name }}',
            name: 'v${{ inputs.tag-name }}',
            prerelease: '${{ inputs.tag-name }}'.includes('-')
          })
