name: 'Comment on a GitHub pull request'

inputs:
  comment:
    description: 'The text of the comment'
    required: true

runs:
  using: "composite"
  steps:
    - name: Comment on PR
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ${{ inputs.comment }}
          })
